var data = {
    colour: {
        names: [
            "Red",
            "Orange",
            "Beige",
            "Yellow",
            "Light green",
            "Green",
            "Dark green",
            "Light blue",
            "Blue",
            "Dark blue",
            "Pink",
            "Purple",
            "Black",
            "White"
        ],
        colours: [
            "red",
            "orange",
            "beige",
            "yellow",
            "lightgreen",
            "green",
            "darkgreen",
            "lightblue",
            "blue",
            "darkblue",
            "pink",
            "purple",
            "black",
            "white"
        ],
        images: []
    },
    colour2: {
        names: [
            "Alice blue",
            "Antique white",
            "Aqua",
            "Aquamarine",
            "Azure",
            "Beige",
            "Bisque",
            "Black",
            "Blanched almond",
            "Blue",
            "Blue violet",
            "Brown",
            "Burly wood",
            "Cadet blue",
            "Chartreuse",
            "Chocolate",
            "Coral",
            "Cornflower blue",
            "Cornsilk",
            "Crimson",
            "Cyan",
            "Dark blue",
            "Dark cyan",
            "Dark golden rod",
            "Dark green",
            "Dark grey",
            "Dark khaki",
            "Dark magenta",
            "Dark olive green",
            "Dark orange",
            "Dark orchid",
            "Dark red",
            "Darks almon",
            "Dark sea green",
            "Dark slate blue",
            "Dark slate grey",
            "Dark turquoise",
            "Dark violet",
            "Deep pink",
            "Deep sky blue",
            "Dim grey",
            "Dodger blue",
            "Fire brick",
            "Floral white",
            "Forest green",
            "Fuchsia",
            "Gainsboro",
            "Ghost white",
            "Gold",
            "Golden rod",
            "Green",
            "Green yellow",
            "Grey",
            "Honey dew",
            "Hot pink",
            "Indian red",
            "Indigo",
            "Ivory",
            "Khaki",
            "Lavender",
            "Lavender blush",
            "Lawn green",
            "Lemon chiffon",
            "Light blue",
            "Light coral",
            "Light cyan",
            "Light golden rod yellow",
            "Light green",
            "Light grey",
            "Light pink",
            "Light salmon",
            "Light sea green",
            "Light sky blue",
            "Light slate grey",
            "Light steel blue",
            "Light yellow",
            "Lime",
            "Lime green",
            "Linen",
            "Magenta",
            "Maroon",
            "Medium aquamarine",
            "Medium blue",
            "Medium orchid",
            "Medium purple",
            "Medium sea green",
            "Medium slate blue",
            "Medium spring green",
            "Medium turquoise",
            "Medium violet red",
            "Midnight blue",
            "Mint cream",
            "Misty rose",
            "Moccasin",
            "Navajo white",
            "Navy",
            "Old lace",
            "Olive",
            "Olive drab",
            "Orange",
            "Orange red",
            "Orchid",
            "Pale golden rod",
            "Pale green",
            "Pale turquoise",
            "Pale violet red",
            "Papaya whip",
            "Peach puff",
            "Peru",
            "Pink",
            "Plum",
            "Powder blue",
            "Purple",
            "Rebecca purple",
            "Red",
            "Rosy brown",
            "Royal blue",
            "Saddle brown",
            "Salmon",
            "Sandy brown",
            "Sea green",
            "Sea shell",
            "Sienna",
            "Silver",
            "Sky blue",
            "Slate blue",
            "Slate grey",
            "Snow",
            "Spring green",
            "Steel blue",
            "Tan",
            "Teal",
            "Thistle",
            "Tomato",
            "Turquoise",
            "Violet",
            "Wheat",
            "White",
            "White smoke",
            "Yellow",
            "Yellow green"
        ],
        colours: [
            "aliceblue",
            "antiquewhite",
            "aqua",
            "aquamarine",
            "azure",
            "beige",
            "bisque",
            "black",
            "blanchedalmond",
            "blue",
            "blueviolet",
            "brown",
            "burlywood",
            "cadetblue",
            "chartreuse",
            "chocolate",
            "coral",
            "cornflowerblue",
            "cornsilk",
            "crimson",
            "cyan",
            "darkblue",
            "darkcyan",
            "darkgoldenrod",
            "darkgreen",
            "darkgrey",
            "darkkhaki",
            "darkmagenta",
            "darkolivegreen",
            "darkorange",
            "darkorchid",
            "darkred",
            "darksalmon",
            "darkseagreen",
            "darkslateblue",
            "darkslategrey",
            "darkturquoise",
            "darkviolet",
            "deeppink",
            "deepskyblue",
            "dimgrey",
            "dodgerblue",
            "firebrick",
            "floralwhite",
            "forestgreen",
            "fuchsia",
            "gainsboro",
            "ghostwhite",
            "gold",
            "goldenrod",
            "green",
            "greenyellow",
            "grey",
            "honeydew",
            "hotpink",
            "indianred",
            "indigo",
            "ivory",
            "khaki",
            "lavender",
            "lavenderblush",
            "lawngreen",
            "lemonchiffon",
            "lightblue",
            "lightcoral",
            "lightcyan",
            "lightgoldenrodyellow",
            "lightgreen",
            "lightgrey",
            "lightpink",
            "lightsalmon",
            "lightseagreen",
            "lightskyblue",
            "lightslategrey",
            "lightsteelblue",
            "lightyellow",
            "lime",
            "limegreen",
            "linen",
            "magenta",
            "maroon",
            "mediumaquamarine",
            "mediumblue",
            "mediumorchid",
            "mediumpurple",
            "mediumseagreen",
            "mediumslateblue",
            "mediumspringgreen",
            "mediumturquoise",
            "mediumvioletred",
            "midnightblue",
            "mintcream",
            "mistyrose",
            "moccasin",
            "navajowhite",
            "navy",
            "oldlace",
            "olive",
            "olivedrab",
            "orange",
            "orangered",
            "orchid",
            "palegoldenrod",
            "palegreen",
            "paleturquoise",
            "palevioletred",
            "papayawhip",
            "peachpuff",
            "peru",
            "pink",
            "plum",
            "powderblue",
            "purple",
            "rebeccapurple",
            "red",
            "rosybrown",
            "royalblue",
            "saddlebrown",
            "salmon",
            "sandybrown",
            "seagreen",
            "seashell",
            "sienna",
            "silver",
            "skyblue",
            "slateblue",
            "slategrey",
            "snow",
            "springgreen",
            "steelblue",
            "tan",
            "teal",
            "thistle",
            "tomato",
            "turquoise",
            "violet",
            "wheat",
            "white",
            "whitesmoke",
            "yellow",
            "yellowgreen"
        ],
        images: []
    },
    twister: {
        names: [
            "Left foot red",
            "Left foot green",
            "Left foot yellow",
            "Left foot blue",
            "Left foot air",
            "Right foot red",
            "Right foot green",
            "Right foot yellow",
            "Right foot blue",
            "Right foot air",
            "Left hand red",
            "Left hand green",
            "Left hand yellow",
            "Left hand blue",
            "Left hand air",
            "Right hand red",
            "Right hand green",
            "Right hand yellow",
            "Right hand blue",
            "Right hand air"
        ],
        colours: [
            "firebrick",
            "forestgreen",
            "gold",
            "royalblue",
            "rebeccapurple",
            "firebrick",
            "forestgreen",
            "gold",
            "royalblue",
            "rebeccapurple",
            "firebrick",
            "forestgreen",
            "gold",
            "royalblue",
            "rebeccapurple",
            "firebrick",
            "forestgreen",
            "gold",
            "royalblue",
            "rebeccapurple"
        ],
        images: []
    }
};